resources:
  creator: P170
  place_of_birth: P19
  place_of_death: P20
  country_of_citizenship: P27
  date_of_birth: P569
  date_of_death: P570
  date_of_foundation_or_creation: P571
  official_website: P856
  gender: P21
  is_in_the_administrative_territorial_entity: P131
  coordinate_location: P625
  located_at_street_address: P969
  postal_code: P281
  geonames_id: P1566
  continent: P30
  country: P17
  freebase_identifier: P646
  father: P22
  start_date: P580
  end_date: P582
  point_in_time: P585
  image: P18
  logo_image: P154
  flag_image: P41
  coat_of_arms_image: P94
  seal_image: P158
  official_language: P37
  wikimedia_language_code: P424
collections:
  official_websites: P856
  instance_of: P31
  subclass_of: P279
  children: P40
